Pertemuan 03 - Data Cleaning
Nama: Athaya Zatus Shawary Lathief
NIM: 250401020181

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Nama": ["A", "B", "C", "D"],
    "Nilai": [80, np.nan, 90, 85]
})

df

  Nama  Nilai
0    A   80.0
1    B    NaN
2    C   90.0
3    D   85.0

In [2]:
df["Nilai"] = df["Nilai"].fillna(df["Nilai"].mean())
df

  Nama  Nilai
0    A   80.0
1    B   85.0
2    C   90.0
3    D   85.0

## Kesimpulan

Data cleaning diperlukan untuk menangani missing value sehingga data lebih siap dianalisis.